apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWpneApOek16TURSYUZ3MDBNekF4TWpneE56TXpNRFJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEQUV1RnNKbkc2Z0I4REJUbXlWSFRCMkxuU0EvV1hzbkJiWFBnYXNSZzVEV2xrUjRuNAo5eDgzNEhnQUhySTB0Qy9LeEcyQkxHSjJPV3pBb1ZtRzhyVG9JTTVjYWFoQU9SN0RqSTVaalJxSTBrQlZoT0o2ClRQMVdaRUhzellwaXNZNXUwNVRwOFR5Rk4vZHI0blFlVnJ6S0QyUVJ0eHJtWklMSWRrNmNxQk9wUTQrelhGWFYKQmZXUHNaNGpINFdPNW5DaWdUbjArMGIxaXZuVkhSMkZsbnBLSUd4YWR6SkluUWQyOExzOEZlSjlrWCtJZnRIYgozSDZuZzh6STA0WHNyU0VzQ0dwSjRVOWQ1ZzR0UlhYcjNrREVHVWZKVVNpQWFNVjJPY2xsdUtaYmZUZ3YvQ2V1CmpQRkRJRVVzU21UMGhWSCtDdEdJOEV4cWpKdTdaOFZrMnV5QkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNUMXdWM3IxbElrZ25IbzlHSwptNWVpKzhJYld6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFUaExmZ3ptY0ZRQjJqS0RJZ1hYZysvZ0pVbXpmClNvMG9vV1RyTmJkVjNMS3lNSTIxdnZBdkh3WnhPY1pBRVQrRUNpZnJHb01jSWFabEt4aTJMUHdPeEdoVlJGWlUKaFdWZlRHZ1hwMjd1UDRsam9Fci8renNQaG05T1JmVXlRNDIvRlBuc2xGWUpYb0FSVEJPQjFRL0E0RWcxcEt1MQpLRlR1a0VDa2JZVFJDdWVadE5MRVZGVnVVU0R5dDIwVk9ldzdYMEk3am5saWtLcm5zcWFRR0YyQXdPc2JlN01ICnhlTDhiSmhaU0xlbkZXemJ1bWpqV3ZWZDEzVUZ3d2p0N1Y5MDNXNjRvOWVOQ1dtaFg2YXNiYUszOFQ5YkRmREkKZThtNW1MNy9EZEdWM0hEQXVrVVFJREZlRFlrVTJ5MHVEbnJ4N3NtclpQeGNXYW13aEEwQTUwZWZtdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://caf12c1e-2805-4e62-a9fb-66cfed461650.k8s.ondigitalocean.com
  name: do-nyc1-desafio3
contexts:
- context:
    cluster: do-nyc1-desafio3
    user: do-nyc1-desafio3-admin
  name: do-nyc1-desafio3
current-context: do-nyc1-desafio3
users:
- name: do-nyc1-desafio3-admin
  user:
    token: dop_v1_59d76c81fe96793f5bdaffd4afb8d0786d75a27b7b99b1fb07849bef1b1557a5
